export type Problem = {
  id: string;
  unit_id: string;
  unit_name: string;
  subject: "수학" | "국어";
  grade: number;
  type: "multiple_choice" | "short_answer";
  difficulty: 1 | 2 | 3 | 4 | 5;
  body: string;
  choices?: string[];
  answer: string;
  explanation: string;
  concept_tags: string[];
  error_type?: "개념미숙" | "계산실수" | "문제해석" | "함정미인지";
};

export type Unit = {
  id: string;
  unit_name: string;
  sub_unit: string;
  standard_code: string;
  concepts: string[];
  problem_count: number;
  available: boolean;
};

export const units: Unit[] = [
  {
    id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    sub_unit: "세 자리 수의 덧셈",
    standard_code: "4수01-04",
    concepts: ["받아올림", "자릿값", "세 자리 수"],
    problem_count: 20,
    available: true,
  },
  {
    id: "unit-2",
    unit_name: "곱셈",
    sub_unit: "두 자리 수의 곱셈",
    standard_code: "4수01-08",
    concepts: ["곱셈구구", "자릿값", "올림"],
    problem_count: 20,
    available: true,
  },
  {
    id: "unit-3",
    unit_name: "나눗셈",
    sub_unit: "나머지가 있는 나눗셈",
    standard_code: "4수01-12",
    concepts: ["나눗셈", "몫", "나머지"],
    problem_count: 20,
    available: true,
  },
  {
    id: "unit-4",
    unit_name: "분수",
    sub_unit: "분수의 덧셈",
    standard_code: "4수01-16",
    concepts: ["분수", "통분", "약분"],
    problem_count: 20,
    available: false,
  },
  {
    id: "unit-5",
    unit_name: "소수",
    sub_unit: "소수의 곱셈",
    standard_code: "4수01-20",
    concepts: ["소수", "소수점", "자릿값"],
    problem_count: 20,
    available: false,
  },
];

export const problems: Problem[] = [
  {
    id: "p1",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 1,
    body: "$$245 + 138$$을 계산하세요.",
    answer: "383",
    explanation: "일의 자리: 5 + 8 = 13, 3을 쓰고 1을 십의 자리로 올립니다.\n십의 자리: 4 + 3 + 1 = 8\n백의 자리: 2 + 1 = 3\n따라서 답은 383입니다.",
    concept_tags: ["받아올림", "세 자리 수"],
  },
  {
    id: "p2",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 2,
    body: "$$367 + 254$$의 값은 얼마입니까?",
    choices: ["611", "621", "521", "612"],
    answer: "621",
    explanation: "일의 자리: 7 + 4 = 11, 1을 쓰고 1을 올립니다.\n십의 자리: 6 + 5 + 1 = 12, 2를 쓰고 1을 올립니다.\n백의 자리: 3 + 2 + 1 = 6\n따라서 답은 621입니다.",
    concept_tags: ["받아올림"],
  },
  {
    id: "p3",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 2,
    body: "$$512 - 287$$을 계산하세요.",
    answer: "225",
    explanation: "일의 자리: 2에서 7을 뺄 수 없으므로 십의 자리에서 10을 빌려옵니다. 12 - 7 = 5\n십의 자리: 0에서 8을 뺄 수 없으므로 백의 자리에서 10을 빌려옵니다. 10 - 8 = 2\n백의 자리: 4 - 2 = 2\n따라서 답은 225입니다.",
    concept_tags: ["받아내림", "세 자리 수"],
  },
  {
    id: "p4",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 3,
    body: "민수는 사탕 $$156$$개를 가지고 있었습니다. 동생에게 $$78$$개를 주고, 친구에게 $$45$$개를 받았습니다. 민수가 지금 가지고 있는 사탕은 몇 개입니까?",
    choices: ["123개", "133개", "113개", "143개"],
    answer: "123개",
    explanation: "민수가 가진 사탕: 156개\n동생에게 준 후: 156 - 78 = 78개\n친구에게 받은 후: 78 + 45 = 123개\n따라서 답은 123개입니다.",
    concept_tags: ["문장제", "덧셈", "뺄셈"],
    error_type: "문제해석",
  },
  {
    id: "p5",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 1,
    body: "$$100 + 200 + 300$$을 계산하세요.",
    answer: "600",
    explanation: "100 + 200 = 300\n300 + 300 = 600\n따라서 답은 600입니다.",
    concept_tags: ["덧셈", "세 자리 수"],
  },
  {
    id: "p6",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 2,
    body: "$$\\square + 125 = 382$$에서 $$\\square$$에 알맞은 수는?",
    choices: ["257", "267", "247", "277"],
    answer: "257",
    explanation: "□ = 382 - 125를 계산합니다.\n382 - 125 = 257\n따라서 □ = 257입니다.",
    concept_tags: ["미지수", "뺄셈"],
  },
  {
    id: "p7",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 3,
    body: "$$463 - 178 + 215$$를 계산하세요.",
    answer: "500",
    explanation: "463 - 178 = 285\n285 + 215 = 500\n따라서 답은 500입니다.",
    concept_tags: ["혼합계산", "덧셈", "뺄셈"],
  },
  {
    id: "p8",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 4,
    body: "어떤 수에서 $$167$$을 빼야 할 것을 잘못하여 더했더니 $$523$$이 되었습니다. 바르게 계산하면 얼마입니까?",
    choices: ["189", "199", "179", "209"],
    answer: "189",
    explanation: "어떤 수를 □라 하면\n□ + 167 = 523이므로 □ = 523 - 167 = 356\n바르게 계산하면: 356 - 167 = 189\n따라서 답은 189입니다.",
    concept_tags: ["문장제", "역연산"],
    error_type: "함정미인지",
  },
  {
    id: "p9",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 2,
    body: "$$789 - 456$$을 계산하세요.",
    answer: "333",
    explanation: "일의 자리: 9 - 6 = 3\n십의 자리: 8 - 5 = 3\n백의 자리: 7 - 4 = 3\n따라서 답은 333입니다.",
    concept_tags: ["뺄셈", "세 자리 수"],
  },
  {
    id: "p10",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 3,
    body: "가장 큰 세 자리 수와 가장 작은 세 자리 수의 차는 얼마입니까?",
    choices: ["899", "889", "900", "800"],
    answer: "899",
    explanation: "가장 큰 세 자리 수: 999\n가장 작은 세 자리 수: 100\n999 - 100 = 899\n따라서 답은 899입니다.",
    concept_tags: ["자릿값", "뺄셈"],
  },
  {
    id: "p11",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 2,
    body: "$$324 + 276$$을 계산하세요.",
    answer: "600",
    explanation: "일의 자리: 4 + 6 = 10, 0을 쓰고 1을 올립니다.\n십의 자리: 2 + 7 + 1 = 10, 0을 쓰고 1을 올립니다.\n백의 자리: 3 + 2 + 1 = 6\n따라서 답은 600입니다.",
    concept_tags: ["받아올림", "덧셈"],
  },
  {
    id: "p12",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 3,
    body: "도서관에 책이 $$428$$권 있었습니다. 새 책 $$156$$권을 구입하고, 오래된 책 $$89$$권을 버렸습니다. 지금 도서관에 있는 책은 몇 권입니까?",
    choices: ["495권", "485권", "505권", "475권"],
    answer: "495권",
    explanation: "처음 책: 428권\n새 책 구입 후: 428 + 156 = 584권\n오래된 책 제거 후: 584 - 89 = 495권\n따라서 답은 495권입니다.",
    concept_tags: ["문장제", "덧셈", "뺄셈"],
  },
  {
    id: "p13",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 4,
    body: "$$\\square - 234 = 567$$에서 $$\\square$$에 알맞은 수를 구하세요.",
    answer: "801",
    explanation: "□ = 567 + 234를 계산합니다.\n567 + 234 = 801\n따라서 □ = 801입니다.",
    concept_tags: ["미지수", "덧셈"],
    error_type: "개념미숙",
  },
  {
    id: "p14",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 2,
    body: "$$500 - 123$$의 값은?",
    choices: ["377", "387", "367", "397"],
    answer: "377",
    explanation: "500 - 123을 계산합니다.\n일의 자리: 0 - 3, 빌려와서 10 - 3 = 7\n십의 자리: 9 - 2 = 7 (빌려줬으므로)\n백의 자리: 4 - 1 = 3\n따라서 답은 377입니다.",
    concept_tags: ["받아내림", "뺄셈"],
  },
  {
    id: "p15",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 3,
    body: "$$199 + 201$$을 계산하세요.",
    answer: "400",
    explanation: "199 + 201 = 200 + 200 = 400\n또는 직접 계산하면:\n일의 자리: 9 + 1 = 10\n십의 자리: 9 + 0 + 1 = 10\n백의 자리: 1 + 2 + 1 = 4\n따라서 답은 400입니다.",
    concept_tags: ["덧셈", "암산"],
  },
  {
    id: "p16",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 4,
    body: "세 수 $$A$$, $$B$$, $$C$$가 있습니다. $$A + B = 500$$이고, $$B + C = 400$$이고, $$A + C = 300$$일 때, $$A$$의 값은?",
    choices: ["200", "150", "100", "250"],
    answer: "200",
    explanation: "세 식을 모두 더하면:\n2(A + B + C) = 1200\nA + B + C = 600\n\nA = 600 - (B + C) = 600 - 400 = 200\n따라서 A = 200입니다.",
    concept_tags: ["연립방정식", "문장제"],
    error_type: "함정미인지",
  },
  {
    id: "p17",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 1,
    body: "$$350 + 150$$을 계산하세요.",
    answer: "500",
    explanation: "350 + 150 = 500\n3 + 1 = 4, 5 + 5 = 10\n따라서 답은 500입니다.",
    concept_tags: ["덧셈", "암산"],
  },
  {
    id: "p18",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 3,
    body: "$$673$$에서 어떤 수를 빼면 $$398$$이 됩니다. 어떤 수는?",
    choices: ["275", "285", "265", "295"],
    answer: "275",
    explanation: "어떤 수 = 673 - 398 = 275\n따라서 어떤 수는 275입니다.",
    concept_tags: ["미지수", "뺄셈"],
  },
  {
    id: "p19",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "short_answer",
    difficulty: 2,
    body: "$$802 - 546$$을 계산하세요.",
    answer: "256",
    explanation: "일의 자리: 2 - 6, 빌려와서 12 - 6 = 6\n십의 자리: 9 - 4 = 5 (10에서 빌려주고 백의 자리에서 받음)\n백의 자리: 7 - 5 = 2\n따라서 답은 256입니다.",
    concept_tags: ["받아내림", "뺄셈"],
    error_type: "계산실수",
  },
  {
    id: "p20",
    unit_id: "unit-1",
    unit_name: "덧셈과 뺄셈",
    subject: "수학",
    grade: 3,
    type: "multiple_choice",
    difficulty: 5,
    body: "$$123 + 234 + 345$$의 값의 각 자릿수의 합은?",
    choices: ["9", "12", "15", "18"],
    answer: "9",
    explanation: "123 + 234 + 345 = 702\n7 + 0 + 2 = 9\n따라서 각 자릿수의 합은 9입니다.",
    concept_tags: ["덧셈", "자릿수"],
    error_type: "문제해석",
  },
];

export const gradeLabels: Record<number, string> = {
  1: "초1",
  2: "초2",
  3: "초3",
  4: "초4",
  5: "초5",
  6: "초6",
  7: "중1",
  8: "중2",
  9: "중3",
  10: "고1",
  11: "고2",
  12: "고3",
};

export function getGradeLabel(grade: number): string {
  return gradeLabels[grade] || `${grade}학년`;
}

export function getDifficultyStars(difficulty: number): string {
  return "★".repeat(difficulty) + "☆".repeat(5 - difficulty);
}
